ABridoux/scout

- README.md
- Sources/Scout/Definitions/Path.swift
- Sources/Scout/Definitions/PathElement.swift
- Sources/Scout/Definitions/PathExplorerError.swift
- Sources/Scout/Extensions/NSRegularExpression+Extensions.swift
- Sources/Scout/Extensions/String+Extension.swift
- Sources/Scout/Implementations/PathExplorerSerialization.swift
- Sources/ScoutCLT/AddCommand.swift
- Sources/ScoutCLT/PathAndValue.swift
- Sources/ScoutCLT/ReadCommand.swift
- Sources/ScoutCLT/ScoutCommand.swift
- Sources/ScoutCLT/SetCommand.swift
- Tests/LinuxMain.swift
- Tests/ScoutTests/PathTests.swift
- Tests/ScoutTests/XCTestManifests.swift
Changed the path with `->` separators to `.` separators. Also changed the array subscription by removing the separator (e.g. `array.[index]` to array[index]`) and the setting value operator from `:` to `=`.
> New path for Command-line tool

- Sources/Scout/Definitions/Path.swift
- Tests/ScoutTests/PathTests.swift
The separator was not used to parse the string in the Path initialisation.
> Path init separator

- Sources/Scout/Definitions/Path.swift
- Tests/ScoutTests/PathTests.swift
The separator was not used to split the string in the `Path` initialisation.
> Custom separator to build a Path

- Sources/Scout/Definitions/Path.swift
- Sources/Scout/Definitions/PathExplorer.swift
- Sources/Scout/Definitions/PathExplorerError.swift
- Sources/Scout/Implementations/PathExplorerSerialization.swift
- Sources/Scout/Implementations/PathExplorerXML.swift
- Sources/ScoutCLT/RuntimeError.swift
- Tests/ScoutTests/PathExplorerSerializationTests.swift
- Tests/ScoutTests/PathTests.swift
With the added `readingPath` property, it is possible to precisely trace where the error occurs in the given path.
Also fixed a bug preventing the initialization of a Path if the root element was an array.
> Subscript errors improved

- Sources/ScoutCLT/ColorDelegates/ColorFile.swift
- Sources/ScoutCLT/ColorDelegates/JSONInjectorDelegate.swift
- Sources/ScoutCLT/ColorDelegates/PlistInjectorColorDelegate.swift
- Sources/ScoutCLT/ColorDelegates/XMLInjectorColorDelegate.swift
- Sources/ScoutCLT/Extensions/String+Extensions.swift
- Sources/ScoutCLT/ReadCommand.swift
- Sources/ScoutCLT/ScoutCommand.swift
- Let the user specify custom colors in the file at *~/scout/Colors.plist*
- Updated the style specification in the string extension
> [#51] Custom colors in a plist file

- Sources/Scout/Definitions/Path.swift
- Sources/Scout/Definitions/PathElement.swift
- Sources/Scout/Definitions/PathElementRepresentable.swift
- Sources/Scout/Definitions/PathExplorer.swift
- Sources/Scout/Implementations/PathExplorerSerialization+PathExplorer.swift
- Sources/Scout/Implementations/PathExplorerSerialization.swift
- Sources/Scout/Implementations/PathExplorerXML+PathExplorer.swift
- Sources/Scout/Implementations/PathExplorerXML.swift
- Tests/ScoutTests/PathTests.swift
Path element is now an enum. To still allow the initialisation of a Path from an array of Strings an Ints, the protocol PathElementRepresentable abstracts PathElement. Thus, it’s required to use the element.pathValue when dealing with PathelEments.
Closes #81
> [#81] Path element refactoring

- Sources/Scout/Implementations/PathExplorerSerialization.swift
Respectively `DictionaryValue` and `ArrayValue`.
Closes #79.
> [#79] Typealiases for [String: Any] and [Any]

- CHANGELOG.md
- Sources/Scout/Constants/Version.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Set.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization.swift
- Setting a value was always writing a String rather than inferring the type for JSON and Plist [#96]
> Setting a value now calls the convert function

- README.md
- Sources/ScoutCLT/Main/DocCommand.swift
- Sources/ScoutCLT/Main/InstallCompletionScriptCommand.swift
- Sources/ScoutCLT/Main/ScoutCommand.swift
- Sources/ScoutCLT/Models/RuntimeError.swift
Scout sub-command `InstallCompletionScriptCommand` to install or re-install the completion script int the right folder depending on the shell and the installed plugins.
Closes #100
> [#100] Completion script installation

- Sources/Scout/Definitions/PathExplorer+Extensions.swift
- Sources/Scout/Definitions/PathExplorer.swift
- Sources/Scout/Definitions/SerializationFormat.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization.swift
- Sources/Scout/Implementations/XML/PathExplorerXML.swift
- Sources/ScoutCLT/Add/AddCommand.swift
- Sources/ScoutCLT/Delete/DeleteCommand.swift
- Sources/ScoutCLT/Main/ScoutCommand.swift
- Sources/ScoutCLT/Read/ReadCommand.swift
- Sources/ScoutCLT/Set/SetCommand.swift
- Tests/ScoutTests/Implementations/PathExplorerSerializationTests.swift
- Tests/ScoutTests/Implementations/PathExplorerXMLTests.swift
Scout replaces the content of those objects by a single string key with a mark. Then replaces this mark with ”…” when exporting the string.
Closes #66
> [#62] Fold dictionaries and arrays at a certain level

- Sources/Scout/Definitions/PathExplorer+Extensions.swift
- Sources/Scout/Definitions/PathExplorer.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Delete.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Delete.swift
- Sources/Scout/Implementations/XML/PathExplorerXML.swift
- Sources/ScoutCLT/Delete/DeleteCommand.swift
- Tests/ScoutTests/Implementations/PathExplorerSerializationTests.swift
- Tests/ScoutTests/Implementations/PathExplorerXMLTests.swift
When deleting a value, it can be specified to also delete the dictionary or the array holding it if the value is the only one in it.
Closes #105
> [#105] Delete arrays or dictionaries when left empty

- Sources/Scout/Definitions/PathElementRepresentable.swift
- Sources/Scout/Definitions/PathExplorerError.swift
- Sources/Scout/Extensions/Int+LastIndex.swift
- Sources/Scout/Models/Bounds.swift
- Tests/ScoutTests/Definitions/PathTests.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests.swift
- Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests.swift
- Tests/ScoutTests/Models/BoundsTests.swift
The lower and upper int properties of the Bounds struct have been replaced by a Bound struct to differentiate first/last and 0
Closes #119
> [#119] Allow single element slicing

- Sources/Scout/Definitions/Path.swift
- Sources/Scout/Definitions/PathElement.swift
- Sources/Scout/Definitions/PathExplorerError.swift
- Sources/Scout/Extensions/AEXMLElement + Extension.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Add.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Delete.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Get.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Set.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Add.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Delete.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Get.swift
- Sources/Scout/Implementations/XML/PathExplorerXML.swift
- Tests/ScoutTests/Definitions/PathTests.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests+Get.swift
- Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests+Get.swift
New PathElement.keysList placed after a dictionary to get the keys as an array.
Powerful when used with the `csv-sep` option in bash/zsh to iterate over the keys.
> [#121] Keys list

- Sources/Scout/Definitions/GroupSample.swift
- Sources/Scout/Definitions/Path.swift
- Sources/Scout/Extensions/AEXMLElement + Extension.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+CSV.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Get.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Set.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+CSV.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Get.swift
- Sources/ScoutCLT/Add/AddCommand.swift
- Sources/ScoutCLT/Add/AddDocumentation.swift
- Sources/ScoutCLT/Delete/DeleteCommand.swift
- Sources/ScoutCLT/Delete/DeleteDocumentation.swift
- Sources/ScoutCLT/Main/ScoutCommand.swift
- Sources/ScoutCLT/Models/Documentation.swift
- Sources/ScoutCLT/Read/ReadCommand.swift
- Sources/ScoutCLT/Read/ReadDocumentation.swift
- Sources/ScoutCLT/Set/SetCommand.swift
- Sources/ScoutCLT/Set/SetDocumentation.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests+Get.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests.swift
- Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests+Get.swift
- Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests.swift
- Dictionary filtering key names changed from path-like to underscore
- Updated in-line documentation
- **Deleted verbose option**. Default behavior is now to output the data if the output or modify option are not specified.
> Refactoring

- Sources/Scout/Definitions/GroupSample.swift
- Sources/Scout/Definitions/Path.swift
- Sources/Scout/Definitions/PathElement.swift
- Sources/Scout/Definitions/PathElementRepresentable.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Get.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Get.swift
- Sources/ScoutCLT/Main/ScoutCommand.swift
- Tests/ScoutTests/Definitions/PathTests.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests+Get.swift
- Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests+Get.swift
- Initialisation from string now uses the `PathElement` `init(from:)` to get the element. New string extensons added for this purpose
- Count replaced by _count in keys names
> Path refactoring

- CONTRIBUTING.md
- README.md
Single-commit version of https://github.com/ABridoux/scout/pull/134.
> Fix minor typos in markdown docs

- Package.resolved
- Package.swift
- Sources/Scout/Definitions/Path.swift
- Sources/Scout/Definitions/PathElement.swift
- Sources/Scout/Definitions/PathExplorerTypes.swift
- Sources/Scout/Definitions/SerializationFormat.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization.swift
- Sources/Scout/Models/Bounds.swift
- Sources/ScoutCLT/Add/AddCommand.swift
- Sources/ScoutCLT/Delete/DeleteCommand.swift
- Sources/ScoutCLT/Extensions/ParsableCommand+Extensions.swift
- Sources/ScoutCLT/Main/ScoutCommand.swift
- Sources/ScoutCLT/Models/PathExplorer+Alias.swift
- Sources/ScoutCLT/Read/ReadCommand.swift
- Sources/ScoutCLT/Set/SetCommand.swift
- Tests/ScoutTests/Definitions/PathTests.swift
- Tests/ScoutTests/Extensions/PathExplorers+Alias.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests.swift
- Tests/ScoutTests/XCTestManifests.swift
YAML is now supported as a serialisable data format.
Also refactored the data reading from a file path or the stream input.
Closes #132
> [#132] YAML integration

- Sources/Scout/Definitions/PathExplorerError.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Delete.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Get.swift
- Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Set.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Delete.swift
- Sources/Scout/Implementations/XML/PathExplorerXML+Get.swift
- Sources/Scout/Models/Bounds.swift
- Tests/ScoutTests/Definitions/PathTests+Extensions.swift
- Tests/ScoutTests/Models/BoundsTests.swift
Negative indexes in a slice are subtracted from the array count rather than the last valid index.
Closes #158
> [150] Changed slicing indexing

- Sources/Scout/Models/Path/Collection+Path.swift
- Sources/Scout/Models/Path/Path+CompactMapElement.swift
- Sources/Scout/Models/Path/Path+Flattening.swift
- Sources/Scout/Models/Path/Path+LastKey.swift
- Sources/Scout/Models/Path/Path+StringConvertible.swift
- Sources/Scout/Models/Path/Path.swift
- Sources/Scout/Models/PathExplorer/PathExplorer+InternalHelpers.swift
- Sources/Scout/PathExplorerImplementations/Serialization/PathExplorerSerialization+Add.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests+Add.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests+Delete.swift
- Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests+Get.swift
- Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests+Get.swift
Closes #171 
- Changed `Path` initialisations. Removed now useless ArraySlice<PathElement> inits and changed `init(pathsElements:)` to `init(elements:)`.
> [#171] Path collections protocol

- Sources/Scout/Extensions/String+Extension.swift
- Sources/Scout/Models/Path/Bounds.swift
- Sources/Scout/Models/Path/Path.swift
- Sources/ScoutCLT/Extensions/Path+Extensions.swift
- Tests/ScoutTests/Definitions/PathTests+Extensions.swift
- Tests/ScoutTests/Definitions/PathTests.swift
- `Path(string:separator:)` does not throw anymore but exit with a precondition failure if the regex is invalid
- Small comments oversights fixed
Closes #171
> Made Path implement RandomAccessCollection

- CHANGELOG.md
- Sources/Scout/Constants/ScoutVersion.swift
- Sources/ScoutCLT/Main/ScoutCommand.swift
The property `FileHandle.standardInput.availableData` was not retrieving all the available data when the size was too large (I misread the documentation).
The proper function is now used with an os version condition.
Closes #192
> Reading from standard input fixed

- Sources/Scout/Models/SerializationFormats.swift
- Tests/ScoutTests/Integration/JSONFormatSerializationTests.swift
Json serialisation from data now supports single values with the `fragmentsAllowed` reading option.
> #190 Json allow fragment

- Sources/Scout/ExplorerValue/ExplorerValue+Add.swift
- Sources/Scout/ExplorerXML/ExplorerXML+Add.swift
- Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Add.swift
The check was made on the path remainder and not the children singularity.
> Fixed adding on single values arrays

- Package.resolved
- Package.swift
- Sources/Scout/ExplorerValue/ExplorerValue+Add.swift
- Sources/Scout/ExplorerValue/ExplorerValue+CSVExport.swift
- Sources/Scout/ExplorerValue/ExplorerValue+CSVImport.swift
- Sources/Scout/ExplorerValue/ExplorerValue+Helpers.swift
- Sources/Scout/ExplorerValue/ExplorerValue.swift
- Sources/Scout/ExplorerXML/ExplorerXML+Add.swift
- Sources/Scout/ExplorerXML/ExplorerXML+CSVExport.swift
- Sources/Scout/ExplorerXML/ExplorerXML+CSVImport.swift
- Sources/Scout/ExplorerXML/ExplorerXML+ExplorerValue.swift
- Sources/Scout/ExplorerXML/ExplorerXML.swift
- Sources/Scout/Extensions/AEXML/AEXMLElement+Children.swift
- Sources/Scout/Extensions/Collection+Extensions.swift
- Sources/Scout/Models/Path/Collection+Path.swift
- Sources/Scout/Models/Path/PathTree.swift
- Sources/Scout/Models/PathExplorer/CodablePathExplorer+Serialization.swift
- Sources/Scout/Models/PathExplorer/PathExplorer+ExploreWithMemory.swift
- Sources/Scout/Models/PathExplorer/SerializablePathExplorer.swift
- Sources/Scout/Models/PathParser/Path+PathParser.swift
- Tests/ScoutTests/Definitions/PathParserTests.swift
- Tests/ScoutTests/PathExplorerTestsSuite/PathExplorer+CSVImport.swift
- Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Add.swift
- Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+CSVExport.swift
- Tests/ScoutTests/PathTree/PathTreeTests.swift
Implement CSV import for `ExplorerValue` and `ExplorerXML`.
The library SwiftCSV is used to parse CSV. Then depending on the headers option, the CSV is parsed as an array of arrays or as an array of dictionary.
With dictionaries, the CSV headers are treated as paths, allowing to deeply customise how the data will be structured.
To optimise this explorer build, the function `add` is not used as it starts from the root to the last element in the explorer. Rather, a `PathTree` is built from the header paths, returning the leafs storing the values. This way, for each row, leafs are populated with new values. Then the dictionary explorer  is built from the tree which is faster than building from a list of path as the last created is explorer will be immediately reused when adding children …
> [#181] CSV import

- Sources/Scout/ExplorerValue/ExplorerValue+Add.swift
- Sources/Scout/ExplorerValue/ExplorerValue+Delete.swift
- Sources/Scout/ExplorerValue/ExplorerValue+Get.swift
- Sources/Scout/ExplorerValue/ExplorerValue+Helpers.swift
- Sources/Scout/ExplorerValue/ExplorerValue+Set.swift
- Sources/Scout/ExplorerXML/ExplorerXML+Add.swift
- Sources/Scout/ExplorerXML/ExplorerXML+Delete.swift
- Sources/Scout/ExplorerXML/ExplorerXML+Get.swift
- Sources/Scout/ExplorerXML/ExplorerXML+Set.swift
- Tests/ScoutTests/ExtensionsTests/ArrayTests.swift
- Tests/ScoutTests/ExtensionsTests/PathExplorerHelperTests.swift
The function was retiring 0 for an empty array rather than throwing an error.
Closes #254
> Compute index fix
