CHANGELOG.md
README.md

Instructions to download and use the executable

Hotfix 0.1.2

---

Makefile
Package.swift

Updated *Makefile* and *Package.swift*

Hotfix 0.1.3

---

Playground/People.json
Playground/People.plist
Playground/People.xml
Sources/Scout/Definitions/KeyType.swift
Sources/Scout/Definitions/Path.swift
Sources/Scout/Definitions/PathExplorer.swift
Sources/Scout/Definitions/PathReaderFactory.swift
Sources/Scout/Implementations/PathExplorerSerialization.swift
Sources/Scout/Implementations/PathExplorerXML.swift
Tests/ScoutTests/Integration/PathExplorerTests_Integration.swift
Tests/ScoutTests/PathTests.swift
Tests/ScoutTests/URL+Extensions.swift

Bugfixes:
- Path init: Getting negative index in array subscript
- Path explorer: negative index when getting
- Xml: array insertion did not work if the element was not the root

Playground plus several bugfixes

---

Sources/ScoutCLT/AddCommand.swift
Sources/ScoutCLT/DeleteCommand.swift
Sources/ScoutCLT/PathAndValue.swift
Sources/ScoutCLT/ReadCommand.swift
Sources/ScoutCLT/SetCommand.swift

Plus minor comments improvements

Modify file option [-m | --modify] for the command line tool

---

Playground/People.json
Playground/People.plist
Playground/People.xml
Sources/Scout/Definitions/Path.swift
Sources/Scout/Definitions/PathExplorerError.swift
Sources/Scout/Implementations/PathExplorerSerialization.swift
Sources/Scout/Implementations/PathExplorerXML.swift
Tests/ScoutTests/Integration/PathExplorerTestsIntegration+Helpers.swift
Tests/ScoutTests/Integration/PathExplorerTests_Integration.swift
Tests/ScoutTests/PathTests.swift

Added support for arrays which are direct children of an array.

Nested arrays support

---

README.md

Master to develop

---

CHANGELOG.md
README.md
Sources/Scout/Constants/Version.swift
Sources/Scout/Implementations/PathExplorerXML+PathExplorer.swift
clt-test.sh

Also added a small test bash script for basic testing. To be improved.

Xml stringValue not empty because of newline

---

Package.resolved
Package.swift
README.md
Sources/ScoutCLT/ReadCommand.swift
Sources/ScoutCLT/ScoutCommand.swift

Visible when outputting a dictionary or array value

[#42] Highlight output

---

Package.resolved
Sources/ScoutCLT/Read/ReadDocumentation.swift

- Lux updated to 0.3.7
- JSON empty strings fixed
- Read documentaion corrected

[#71] Json empty strings

---

Sources/Scout/Definitions/KeyType.swift
Sources/Scout/Definitions/Path.swift
Sources/Scout/Definitions/PathElement.swift
Sources/Scout/Definitions/PathExplorer.swift
Sources/Scout/Definitions/PathExplorerError.swift
Sources/Scout/Implementations/PathExplorerSerialization+PathExplorer.swift
Sources/Scout/Implementations/PathExplorerSerialization.swift
Sources/Scout/Implementations/PathExplorerXML+PathExplorer.swift
Sources/Scout/Implementations/PathExplorerXML.swift
Tests/ScoutTests/Extensions/URL+Extensions.swift
Tests/ScoutTests/Extensions/XCTestCase+Extensions.swift
Tests/ScoutTests/PathExplorerSerializationTests.swift
Tests/ScoutTests/PathExplorerXMLTests.swift
Tests/ScoutTests/PathTests.swift

- `PathElement.count`  '[#]' to return the count of the previous array/dict
- Path refactoring
Closees #76

[#76] Array count Path element

---

.swiftpm/xcode/xcshareddata/xcschemes/Scout.xcscheme
README.md
Sources/Scout/Definitions/KeyAllowedType.swift
Sources/Scout/Definitions/Path.swift
Sources/Scout/Definitions/PathElement.swift
Sources/Scout/Definitions/PathExplorer+Extensions.swift
Sources/Scout/Definitions/SerializationFormat.swift
Sources/Scout/Extensions/PathExplorerSerialization + ValueType.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Add.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Delete.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Get.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Set.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization.swift
Sources/Scout/Implementations/XML/PathExplorerXML+Add.swift
Sources/Scout/Implementations/XML/PathExplorerXML+Delete.swift
Sources/Scout/Implementations/XML/PathExplorerXML+Set.swift
Tests/ScoutTests/PathExplorerSerializationTests.swift
Tests/ScoutTests/PathExplorerXMLTests.swift

New functions to make the code more readable and more easily testable

Refactoring value types

---

Package.resolved
Sources/Scout/Definitions/Path.swift
Sources/Scout/Definitions/PathExplorer.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization.swift
Sources/Scout/Implementations/XML/PathExplorerXML.swift
Sources/ScoutCLT/Add/AddCommand.swift
Sources/ScoutCLT/Delete/DeleteCommand.swift
Sources/ScoutCLT/Extensions/ParsableCommand+PathCompletion.swift
Sources/ScoutCLT/Extensions/Path+Extensions.swift
Sources/ScoutCLT/Main/DocCommand.swift
Sources/ScoutCLT/Models/Command.swift
Sources/ScoutCLT/Read/ReadCommand.swift
Sources/ScoutCLT/Set/SetCommand.swift
Tests/ScoutTests/Integration/PathExplorerTestsIntegration+Helpers.swift

- Auto-completion for commands with Argument Parser 0.2.2
- Also added more precise testing for setting a value
Closes #94

[#94] Auto completion

---

Sources/Scout/Definitions/Path.swift
Sources/Scout/Definitions/PathExplorer+Extensions.swift
Sources/Scout/Definitions/PathExplorerError.swift
Sources/Scout/Extensions/PathExplorerSerialization + GroupValueType.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Delete.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Get.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Set.swift
Sources/Scout/Implementations/XML/PathExplorerXML+Delete.swift
Sources/Scout/Implementations/XML/PathExplorerXML+Get.swift
Sources/Scout/Implementations/XML/PathExplorerXML.swift
Sources/ScoutCLT/Extensions/Path+Extensions.swift
Tests/ScoutTests/Implementations/PathExplorerSerializationTests.swift
Tests/ScoutTests/Implementations/PathExplorerXMLTests.swift

After a slice, it is possible to target a common key in the dictionaries or a common index in the arrays in the slice to read it or to delete it.
closes #102

[#102] Reading and deleting a value after slicing

---

Sources/Scout/Definitions/PathElementRepresentable.swift
Sources/Scout/Definitions/PathExplorerError.swift
Sources/Scout/Extensions/Int+MaxIndex.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+CSV.swift
Sources/Scout/Implementations/XML/PathExplorerXML+CSV.swift
Sources/Scout/Models/Bounds.swift
Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests.swift
Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests.swift
Tests/ScoutTests/Models/BoundsTests.swift

- Array slicing upper bound negative index possible
- CSV label as first value in line when dealing with dictionaries of arrays

Last improvements

---

CODE_OF_CONDUCT.md

Forgot to remove the contact method in the last PR...

Remove contact method from CoC

---

Sources/ScoutCLT/Add/AddCommand.swift
Sources/ScoutCLT/Delete/DeleteCommand.swift
Sources/ScoutCLT/Models/SADCommand.swift
Sources/ScoutCLT/Read/ReadCommand.swift
Sources/ScoutCLT/Set/SetCommand.swift

New  `SADCommand` protocol to centralise the logic for the Set/Add/Delete commands.

Refactored SAD commands

---

Package.resolved
Package.swift
Sources/ScoutCLT/ColorDelegates/ColorFile.swift
Sources/ScoutCLT/ColorDelegates/File.swift
Sources/ScoutCLT/Main/ScoutCommand.swift

[#142] Updated to Lux/develop to highlight Yaml

---

.swiftpm/xcode/xcshareddata/xcschemes/ScoutCLT.xcscheme
Package.resolved
Package.swift
Playground/Commands.md
Playground/People.json
Playground/People.plist
Playground/People.xml
Playground/People.yml
Sources/Scout/Implementations/Serialization/PathExplorerSerialization+Add.swift
Sources/Scout/Implementations/XML/PathExplorerXML+Add.swift
Sources/Scout/Implementations/XML/PathExplorerXML+Paths.swift
Sources/ScoutCLT/Add/AddDocumentation.swift
Sources/ScoutCLT/AdvancedTopicsDoc/AdvancedTopic.swift
Sources/ScoutCLT/AdvancedTopicsDoc/AdvandedPredicates.swift
Sources/ScoutCLT/Delete/DeleteDocumentation.swift
Sources/ScoutCLT/Extensions/ArgumentHelp+Extensions.swift
Sources/ScoutCLT/Extensions/String+Extensions.swift
Sources/ScoutCLT/Main/DocCommand.swift
Sources/ScoutCLT/Main/ScoutCommand.swift
Sources/ScoutCLT/Main/ScoutMainCommand.swift
Sources/ScoutCLT/Models/Command.swift
Sources/ScoutCLT/Models/Documentation.swift
Sources/ScoutCLT/Models/SADCommand.swift
Sources/ScoutCLT/Paths/PathsDocumentation.swift
Sources/ScoutCLT/Read/ReadDocumentation.swift
Sources/ScoutCLT/Set/SetDocumentation.swift
Tests/ScoutTests/Implementations/Serialization/PathExplorerSerializationTests+Add.swift
Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests+Add.swift
Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests+Paths.swift
Tests/ScoutTests/Integration/PathExplorerTests_Integration.swift

- Updated program documentation commands
- Added ne advanced commendation topics
- Updated the playground
- Fixed minor faults discovered while testing playground
Closes #150

[#150] Update doc

---

Sources/Scout/Definitions/PathExplorer+Extensions.swift
Sources/Scout/Definitions/PathExplorer+FunctionsHelper.swift
Sources/Scout/Definitions/PathExplorer.swift
Sources/Scout/Implementations/Serialization/PathExplorerSerialization.swift
Sources/Scout/Implementations/XML/PathExplorerXML.swift
Sources/ScoutCLT/Delete/DeleteKeyCommand.swift
Tests/ScoutTests/Implementations/XML/PathExplorerXMLTests+Delete.swift

Updated `PathExplorer` interface and default functions implementations.

[#163] Path explorer interface

---

Sources/Scout/Extensions/NSRegularExpression+Extensions.swift
Sources/Scout/Extensions/String+Extension.swift
Sources/Scout/Models/Path/Path+Regex.swift
Sources/Scout/Models/Path/Path.swift
Sources/Scout/Models/Path/PathElementRepresentable.swift
Sources/Scout/Models/Path/PathError.swift
Tests/ScoutTests/Definitions/PathTests.swift

- The Path init using a custom separator will throw a relevant error
- Small refactoring

Made the path init using custom separator throw

---

Sources/Scout/Models/PathExplorer/PathExplorer+ConvenienceFunctions.swift
Sources/Scout/Models/PathExplorer/PathExplorer+InternalHelpers.swift
Sources/Scout/Models/PathExplorer/PathExplorer+Literal.swift
Sources/Scout/PathExplorerImplementations/Serialization/PathExplorerSerialization+CSV.swift
Sources/Scout/PathExplorerImplementations/Serialization/PathExplorerSerialization+Delete.swift
Sources/Scout/PathExplorerImplementations/Serialization/PathExplorerSerialization+Get.swift
Sources/Scout/PathExplorerImplementations/Serialization/PathExplorerSerialization+Set.swift
Sources/Scout/PathExplorerImplementations/Serialization/PathExplorerSerialization.swift
Sources/Scout/PathExplorerImplementations/XML/PathExplorerXML+Add.swift
Sources/Scout/PathExplorerImplementations/XML/PathExplorerXML+CSV.swift
Sources/Scout/PathExplorerImplementations/XML/PathExplorerXML+Delete.swift
Sources/Scout/PathExplorerImplementations/XML/PathExplorerXML+ExportFormat.swift
Sources/Scout/PathExplorerImplementations/XML/PathExplorerXML+Get.swift
Sources/ScoutCLT/Main/DocCommand.swift

Added sections in PathExplorer implementations

Small refactoring

---

Sources/Scout/Extensions/String+Jaro-Winkler.swift

Look for a max immediately rather than filter

Refactored Jaro winkler best match

---

Sources/Scout/Models/Path/PathElement.swift
Sources/Scout/Models/Path/PathElementRepresentable.swift

Changed the computed property names to avoid confusion and added comments.

Refactored string extension with PathElement

---

Sources/Scout/Extensions/Array+Extensions.swift
Sources/Scout/Extensions/Dictionary+Extensions.swift
Sources/Scout/Extensions/File.swift
Sources/Scout/Extensions/Slice+Etensions.swift
Sources/Scout/Models/PathExplorer/PathExplorer+InternalHelpers.swift
Sources/Scout/Models/PathExplorer/PathExplorerBis+Convenience.swift
Sources/Scout/Models/PathExplorer/PathExplorerBis.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType+Delete.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType+Get.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType+Helpers.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType+Set.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueTypeError.swift
Sources/Scout/PathExplorerImplementations/XML/PathExplorerXML.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Delete.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Get.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Set.swift

Set and delete unctions on `ValueType`
Closes #202

[#202] Set functions

---

Sources/Scout/Models/PathExplorer/PathExplorerBis+Convenience.swift
Sources/Scout/Models/PathExplorer/PathExplorerBis.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType+Add.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType+Get.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Add.swift

`ValueType` add functions
Closes #204

Add functions

---

Sources/Scout/Models/Path/Path+LastKey.swift
Sources/Scout/Models/PathExplorer/PathExplorerBis+Convenience.swift
Sources/Scout/Models/PathExplorer/PathExplorerBis.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType+PathsListing.swift
Sources/Scout/PathExplorerImplementations/ValueType/ValueType.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+PathsListing.swift

Add functions for `ValueType`.
Also refactored `PathExplorerBis` convenience

Paths listing for ValueType

---

Sources/Scout/Constants/Folding.swift
Sources/Scout/ExplorerValueSerialization/CodableFormat.swift
Sources/Scout/Models/PathExplorer/CodableFormatPathExplorer.swift
Sources/Scout/Models/PathExplorer/PathExplorerBis+Convenience.swift
Sources/Scout/Models/PathExplorer/SerializablePathExplorer.swift
Sources/Scout/PathExplorerImplementations/ExplorerValue/ExplorerValue+CSV.swift
Sources/Scout/PathExplorerImplementations/ExplorerValue/ExplorerValue+Folded.swift
Sources/Scout/PathExplorerImplementations/ExplorerValue/ExplorerValue+Set.swift
Sources/Scout/PathExplorerImplementations/ExplorerValue/ExplorerValue.swift
Sources/Scout/PathExplorerImplementations/ExplorerValue/SerializationError.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+CSVExport.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Fold.swift

Export CSV function and folding
Closes #206

[#206] Export functions

---

CHANGELOG.md
Sources/Scout/Constants/ScoutVersion.swift
Sources/ScoutCLT/Main/ScoutCommand.swift

- Reading from standard input temporary fix for deprecation issue [#191]

[hot] Read standard input

---

Sources/Scout/ExplorerValue/ExplorerValue+Delete.swift

ExplorerValue delete functions did not use them.

Removec useless group sample handling

---

Sources/Scout/ExplorerValue/ExplorerValue+Add.swift
Sources/Scout/ExplorerValue/ExplorerValue+CSVExport.swift
Sources/Scout/ExplorerValue/ExplorerValue+Delete.swift
Sources/Scout/ExplorerValue/ExplorerValue+Folded.swift
Sources/Scout/ExplorerValue/ExplorerValue+Get.swift
Sources/Scout/ExplorerValue/ExplorerValue+PathsListing.swift
Sources/Scout/ExplorerValue/ExplorerValue+Set.swift
Sources/Scout/ExplorerValue/ExplorerValue.swift
Sources/Scout/ExplorerValueSerialization/ExplorerValueConvertible+Codable/Decoding/ExplorerValueDecodingContainer.swift
Sources/Scout/ExplorerXML/ExplorerXML+Add.swift
Sources/Scout/ExplorerXML/ExplorerXML+Delete.swift
Sources/Scout/ExplorerXML/ExplorerXML+Get.swift
Sources/Scout/ExplorerXML/ExplorerXML+PathsListing.swift
Sources/Scout/ExplorerXML/ExplorerXML+Set.swift
Sources/Scout/ExplorerXML/ExplorerXML.swift
Sources/Scout/Models/Path/Path+CompactMapElement.swift
Sources/Scout/Models/Path/Path+LastElement.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+Get.swift

- Removed filter detailed name
- Removed filter and slice
- ExplorerXML removed lastGroupSample handling
- cutHead for collections

Remove group sample

---

Sources/Scout/ExplorerValue/ExplorerValue+Add.swift
Sources/Scout/ExplorerValue/ExplorerValue+Delete.swift
Sources/Scout/ExplorerValue/ExplorerValue+Get.swift
Sources/Scout/ExplorerValue/ExplorerValue+Set.swift
Sources/Scout/ExplorerValue/ExplorerValue.swift
Sources/Scout/ExplorerXML/ExplorerXML+Add.swift
Sources/Scout/ExplorerXML/ExplorerXML+Delete.swift
Sources/Scout/ExplorerXML/ExplorerXML+Get.swift
Sources/Scout/ExplorerXML/ExplorerXML+Set.swift
Sources/Scout/ExplorerXML/ExplorerXML.swift
Sources/Scout/Models/Path/Bounds.swift
Sources/Scout/Models/Path/Path+LastElement.swift

- Changed switch with one statements
- Renaming

Refactoring

---

Sources/Scout/ExplorerXML/ExplorerXML+ExplorerValue.swift
Sources/Scout/ExplorerXML/ExplorerXML.swift

Added functions to customise array and dictionary export

Array and dictionary exports

---

Sources/Scout/ExplorerValue/ExplorerValue.swift
Sources/Scout/ExplorerValueSerialization/ExplorerValueConvertible+Codable/Decoding/ExplorerValueDecodingContainer.swift
Sources/Scout/ExplorerValueSerialization/ExplorerValueConvertible+Codable/Decoding/ExplorerValueSingleDecodingContainer.swift
Sources/Scout/ExplorerValueSerialization/ExplorerValueConvertible+Codable/Decoding/ExplorerValueUnkeyedDecodingContainer.swift
Sources/Scout/ExplorerValueSerialization/ExplorerValueConvertible+Codable/Encoding/ExplorerValueEncodingContainer.swift
Sources/Scout/ExplorerValueSerialization/ExplorerValueConvertible+Codable/Encoding/ExplorerValueSingleEncodingContainer.swift
Sources/Scout/ExplorerValueSerialization/ExplorerValueConvertible+Codable/Encoding/ExplorerValueUnkeyedEncodingContainer.swift

Also, a new date property is implement for ExplorerValue.
Closes #239

Date was not properly coded

---

Sources/Scout/ExplorerXML/ExplorerXML+Add.swift
Sources/Scout/ExplorerXML/ExplorerXML+Set.swift
Sources/Scout/ExplorerXML/ExplorerXML.swift
Sources/Scout/Models/PathExplorer/CodablePathExplorer.swift
Sources/Scout/Models/PathExplorer/PathExplorer.swift

- Added missing ExplorerXML specifications for add and set features.
- Deprecated PathExplorer.real

[#241] Missing xml values

---

.swiftpm/xcode/xcshareddata/xcschemes/ScoutCLT.xcscheme
Sources/Scout/ExplorerValue/ExplorerValue.swift
Sources/Scout/ExplorerValueSerialization/CodableFormat.swift
Sources/Scout/Extensions/CodingKey+Extensions.swift
Sources/ScoutCLT/Main/PathExplorerInputCommand.swift
Sources/ScoutCLT/Models/PathExplorer+Alias.swift

Added missing date decoding
closes #239

Date decoding

---

CHANGELOG.md
Sources/Parsing/Parser+Operators.swift
Sources/Parsing/Parser+Types.swift
Sources/Scout/Constants/ScoutVersion.swift
Sources/Scout/ExplorerValue/ExplorerValue+CSVExport.swift
Sources/Scout/ExplorerValue/ExplorerValue+Get.swift
Sources/Scout/ExplorerValue/ExplorerValue.swift
Sources/Scout/ExplorerValueSerialization/CodableFormat.swift
Sources/Scout/ExplorerXML/ExplorerXML+CSVExport.swift
Sources/Scout/Models/PathExplorer/PathExplorer+ExploreWithMemory.swift
Sources/ScoutCLT/Add/AddDocumentation.swift
Sources/ScoutCLT/CSVCommand.swift
Sources/ScoutCLT/Delete/DeleteDocumentation.swift
Sources/ScoutCLT/Extensions/ArgumentParserConformance/ParsableCommand+Extensions.swift
Sources/ScoutCLT/Extensions/ArgumentParserConformance/PathAndValue+ArgumentParser.swift
Sources/ScoutCLT/Main/InstallCompletionScriptCommand.swift
Sources/ScoutCLT/Models/Documentation.swift
Sources/ScoutCLT/Models/SADCommand.swift
Sources/ScoutCLT/Read/ReadCommand.swift
Sources/ScoutCLT/Read/ReadDocumentation.swift
Sources/ScoutCLT/Set/SetDocumentation.swift
Sources/ScoutCLTCore/Models/ExportCommand.swift
Sources/ScoutCLTCore/Models/ExportFormat.swift
Tests/ScoutTests/PathExplorerTestsSuite/PathExplorerTests+CSVExport.swift

- Date decoding and `PathExplorer.date` [#239]
- `ExplorerXML` add and set features works with `ExplroerXML` values [#241]

Release 4.0.1

---

Sources/Scout/Extensions/String+Jaro-Winkler.swift
Tests/ScoutTests/ExtensionsTests/String+Jaro-WinklerTests.swift

Fixed Jaro-Winkler crash when comparing two single characters
